# Site settings
title: Orange
description: Orange Programming Language
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://orange-lang.org" # the base hostname & protocol for your site
github_username: orange-lang
github_repo: orange

# Build settings
markdown: kramdown

collections:
- sections